### ISSUE TITLE
unexpected keyword argument 'allow_unicode'

### ISSUE THREAD

**Issue by Nirvanatin** [HoloArchivists/tslazer#11]
Is it possible to run the tslazer in Windows?

```
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\twitterspace\tslazer\tslazer.py", line 43, in <module>
    TwitterSpace.TwitterSpace(space_id=args.space_id, filenameformat=args.fileformat, path=args.path, withChat=args.withchat, cookiesPath=args.cookies)
  File "C:\Users\USER\Desktop\twitterspace\tslazer\TwitterSpace.py", line 524, in __init__
    self.filenameformat = slugify(self.filenameformat, allow_unicode=True, lowercase=False, separator='_')
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: slugify() got an unexpected keyword argument 'allow_unicode'
```

**Comment by fireattack** [comment]
Try to update slugify:

```
pip install python-slugify -U
```
