### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by NoelArzola** [HoloArchivists/tslazer#3]
Space ID is 1kvJpmLywvXxE
In the TwitterSpace class I'm failing in the condition if metadata != None on 219
The try fails so I receive the exception
Through debugging I've narrowed it down to `subprocess.run(command, cwd=path)` in the else of the try
I looked what's being passed into the function:

command: `ffmpeg -f concat -safe 0 -i chunkindex.txt -c copy -metadata title="AMA w/Kelsey Hightower - The Distinguished Gentleman" -metadata artist="escobyte" AMA_w_Kelsey_Hightower_The_Distinguished_Gentleman.m4a -loglevel fatal`

path: `/Users/{user}/Downloads/tslazer-master`

Here's the traceback I got when moving the same command into the exception so it runs regardless. chunkindex.txt exists. In fact, I can run this same command manually in the terminal but it results in a file that is mix and mashed from the chunks concatenating out of order. 

```
Traceback (most recent call last):
  File "/Users/{user}/Downloads/tslazer-master/TwitterSpace.py", line 228, in downloadChunks
    subprocess.run(command, cwd=path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg -f concat -safe 0 -i chunkindex.txt -c copy -metadata title="AMA w/Kelsey Hightower - The Distinguished Gentleman" -metadata artist="escobyte" AMA_w_Kelsey_Hightower_The_Distinguished_Gentleman.m4a -loglevel fatal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/{user}/Downloads/tslazer-master/./tslazer.py", line 39, in <module>
    TwitterSpace.TwitterSpace(space_id=args.space_id, filenameformat=args.fileformat, path=args.path, withChat=args.withchat)
  File "/Users/{user}/Downloads/tslazer-master/TwitterSpace.py", line 349, in __init__
    TwitterSpace.downloadChunks(livechunks, self.filenameformat, self.path, m4aMetadata)
  File "/Users/{user}/Downloads/tslazer-master/TwitterSpace.py", line 235, in downloadChunks
    subprocess.run(command, cwd=path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg -f concat -safe 0 -i chunkindex.txt -c copy -metadata title="AMA w/Kelsey Hightower - The Distinguished Gentleman" -metadata artist="escobyte" AMA_w_Kelsey_Hightower_The_Distinguished_Gentleman.m4a -loglevel fatal'
```

Okay so trying to debug a bit in subprocess.py self._execute_child seems to fail and it's being passed the arguments:
`None None 0 False -1 -1 -1 -1 -1 -1 True None None None -1 False`

Not really sure how to get anything useful from line 1823 here

**Comment by ef1500** [comment]
Hello there, thanks for taking the time to open an issue.  
Are you using the most recent version of the script? I was unable to reproduce the issue. 
![2022-12-14_21-28](https://user-images.githubusercontent.com/45581646/207765694-0b9ecff3-be6c-41b4-858e-87632be8e829.png)

The issue seems to be that you do not have ffmpeg installed, or you do not have it installed properly.

1. Type ffmepg into your terminal, if it doesn't recognize then command then you don't have it.
 - If you don't have ffmpeg installed, you can grab the latest binaries from [here](https://github.com/GyanD/codexffmpeg/releases/download/2022-12-11-git-c3e20f78b0/ffmpeg-2022-12-11-git-c3e20f78b0-essentials_build.zip) (I assume you're using windows)
 - you will need to add the location of the bin folder to your PATH variable. This will allow you to run the ffmpeg command from the terminal.
2. If that doesn't fix anything, try using `git pull` to update the repository to the latest version.

Let me know if that helps you!

**Comment by NoelArzola** [comment]
Thanks for the response!
Oh, sorry yeah should've mentioned I'm on a Mac, I installed ffmpeg through brew, and I am on the most recent version of Master. I can run ffmpeg from the same folder it just resulted in a mixed and matched file. I tried the overhaul branch and I get the same Traceback BUT when I copied the ffmpeg command from this and ran it, it actually created the file this time.

```
Traceback (most recent call last):
  File "/Users/{user}/Downloads/tslazer/tslazer.py", line 92, in <module>
    space_dl.download_from_cli(space_id=args.space_id, format_str=args.fileformat,
  File "/Users/{user}/Downloads/tslazer/tsengine_config.py", line 254, in download_from_cli
    aac_downloader.concat_chunks(download_path,
  File "/Users/{user}/Downloads/tslazer/downloader/aac_downloader.py", line 109, in concat_chunks
    subprocess.run(command, cwd=download_path, check=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 950, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1822, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg -f concat -safe 0 -i chunkindex.txt -c copy "no_meta_1kvJpmLywvXxE.m4a" -loglevel fatal'
```

**Comment by ef1500** [comment]
Sorry for the extremely delayed response, but I've put the "help wanted" tag on this issue, as I'm not really sure what the issue is or how to reproduce it.

**Comment by NoelArzola** [comment]
No worries! It feels edge case since I had success running the same commands in the CLI. I'm okay with closing this!
